version: '3.5'

services:
  api:
    container_name: llm-api
    image: llm-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:6672
    env_file:
      - .env
    volumes:
      - ./unit_config.json:/docker-entrypoint.d/unit_config.json
    networks:
      - llm_wrap_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - ${WEB_RABBIT_MQ}:15672
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - llm_wrap_network

  redis:
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/var/lib/data
    networks:
      - llm_wrap_network

networks:
  llm_wrap_network:
    name: llm_wrap_network
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
