version: '3.8'

services:
  llm:
    container_name: llm-worker
    image: llm-core:latest
#    runtime: nvidia
#    deploy:
#      resources:
#        limits:
#          # cpus: 5
#          memory: 100G
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
#    volumes:
#      - <your_path_to_data_in_docker>:/data
    ports:
      - ${LLM_WORKER_PORT}:8672
    networks:
      - llm_wrap_network
    restart: unless-stopped

networks:
  llm_wrap_network:
    name: llm_wrap_network
    driver: bridge
